### ISSUE TITLE
Venti is running even it's configmap is wrong

### ISSUE THREAD

**Issue by vividcloudpark** [kuoss/venti#156]
**Describe the bug**

`time="2024-07-25T00:36:21Z" level=warning msg="loadAlertRuleFileFromFilename err: unmarshalStrict err: yaml: line 20: could not find expected ':'" file="store.go:32"`

Venti should not running when it's venti-alertrules configmap is wrong, but it run, and cannot access "alert" tab.

**To Reproduce**
1. put some wrong phrase in below configmap
`kubectl -n kube-system edit cm venti-alertrules`

2.Then restart venti, and look head of venti.

**Expected behavior**
Venti should not running 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jmnote** [comment]
Could you let us know which version you are using?

**Comment by vividcloudpark** [comment]
> Could you let us know which version you are using?

It occured at v0.2.0.

**Comment by jmnote** [comment]
Thanks for reporting the bug. But the bug was already reported in Issue #140 and fixed in PR #141. It does not occur in versions v0.2.20 and later.
https://github.com/kuoss/venti/pull/141/files#diff-3d7cb26ac9af9c94517a8e1a273d982686b1e9b76879153f2de267e7674e7a50L31-R30

Stack trace for v0.2.0
- main https://github.com/kuoss/venti/blob/v0.2.0/main.go#L23-L27
- store.NewStores https://github.com/kuoss/venti/blob/v0.2.0/pkg/store/store.go#L30-L32
- alertrule.New https://github.com/kuoss/venti/blob/v0.2.0/pkg/store/alertrule/alertrule.go#L29-L33

Stack trace for v0.2.20
- main https://github.com/kuoss/venti/blob/v0.2.20/main.go#L25-L28
- service.NewServices https://github.com/kuoss/venti/blob/v0.2.20/pkg/service/service.go#L32-L35
- alertrule.New https://github.com/kuoss/venti/blob/v0.2.20/pkg/service/alertrule/alertrule.go#L28-L31
